---
### Excluding directories

# Directories below will not be scanned at all
exclude_paths:
  - vendor
  - db
  - config
  - script
  - lib/crawler
  - lib/scraper
  - lib/task/adhoc
  - redis-3.2.4

### Directory specific configuration

# You can configure smells on a per-directory base.
# E.g. the classic Rails case: controllers smell of NestedIterators (see /docs/Nested-Iterators.md) and
directories:
  "app/models":
    TooManyMethods:
      enabled: false
  "app/controllers":
    NestedIterators:
      max_allowed_nesting: 3
    IrresponsibleModule:
      enabled: false
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    ControlParameter:
      enabled: false
  "app/validators":
    ControlParameter:
      enabled: false
  "app/lib/facebook":
    UncommunicativeModuleName:
      enabled: false
    ManualDispatch:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
  "app/batches/expedia/hotels/":
    DataClump:
      enabled: false
    TooManyMethods:
      enabled: false
    TooManyStatements:
      enabled: false
    DuplicateMethodCall:
      enabled: false

### Generic smell configuration

# You can disable smells completely
detectors:
  ManualDispatch:
    exclude:
      - CacheSupporter#self.find_with_cache
  Attribute:
   enabled: false
   exclude: []
  BooleanParameter:
    enabled: true
    exclude: []
  ClassVariable:
    enabled: true
    exclude: []
  ControlParameter:
    enabled: true
    exclude: []
  DataClump:
    enabled: true
    exclude: []
    max_copies: 9
    min_clump_size: 2
  DuplicateMethodCall:
    enabled: true
    exclude: []
    max_calls: 3 # [sideci] ease 1 to 2
    allow_calls: []
  FeatureEnvy:
    enabled: false
    exclude: []
  IrresponsibleModule:
    enabled: false
    exclude: []
  LongParameterList:
    enabled: true
    exclude: []
    max_params: 5
    overrides:
      initialize:
        max_params: 5
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 3
  ModuleInitialize:
    enabled: true
    exclude: []
  NestedIterators:
    enabled: true
    exclude: []
    max_allowed_nesting: 4
    ignore_iterators:
    - tap
  NilCheck:
    enabled: true
    exclude: []
  MissingSafeMethod:
    enabled: false
    exclude: []
  RepeatedConditional:
    enabled: true
    exclude: []
    max_ifs: 5
  TooManyInstanceVariables:
    enabled: true
    exclude: []
    max_instance_variables: 5
  TooManyMethods:
    enabled: true
    exclude:
      - ChatUnit
    max_methods: 30
  TooManyStatements:
    enabled: true
    exclude:
    - initialize
    - AdminAbility
    max_statements: 20 # [sideci] ease 5 to 10
  UncommunicativeMethodName:
    enabled: true
    exclude: []
    reject:
      - "/^[a-z]$/"
      - "/[A-Z]/"
    accept: []
  UncommunicativeModuleName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
    accept: []
  UncommunicativeParameterName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
      - "/^_/"
    accept: []
  UncommunicativeVariableName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept:
    - _
  UnusedParameters:
    enabled: true
    exclude: []
  TooManyConstants:
    enabled: false
  
  BooleanParameter:
    enabled: false
  UtilityFunction:
    enabled: false
  NilCheck:
    enabled: false
  ControlParameter:
    enabled: false
  InstanceVariableAssumption:
    enabled: true
    exclude:
      - InfiniLCC::Routes::FetchSupplierRoutesBatch
