AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'config/routes.rb'
    - 'bin/*'
    - 'Gemfile'
    - 'config/**/*'
  TargetRubyVersion: 2.5
  DisplayCopNames: true


Layout/MultilineMethodCallIndentation:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: true

Layout/AlignParameters:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: true

Style/Attr:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true

Style/BlockComments:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: false

Style/CaseEquality:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Style/EmptyElse:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/EndBlock:
  Enabled: true

Layout/EndOfLine:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Naming/FileName:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true

Style/FlipFlop:
  Enabled: true

Style/For:
  Enabled: true

# strftimeの%dで警告を出すためdisable
# https://github.com/onk/onkcop/blob/master/config/rubocop.yml#L254
Style/FormatString:
  Enabled: false

Style/GlobalVars:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PercentQLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAfterMethodName:
  Enabled: false

Layout/SpaceAfterNot:
  Enabled: false

Layout/SpaceAfterSemicolon:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Layout/SpaceBeforeSemicolon:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceAroundBlockParameters:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/Tab:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/UnneededCapitalW:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Naming/VariableName:
  Enabled: false

Style/WhenThen:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false

Lint/StringConversionInInterpolation:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/UselessAccessModifier:
  Exclude:
    - app/queries/mongo/query.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled:
  Exclude:
    - "spec/**/*"

Performance/RegexpMatch:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Performance/Count:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: true
  Exclude:
    - "app/models/concerns/searchable/base.rb"

Naming/UncommunicativeMethodParamName:
  MinNameLength: 2
  Enabled: true

Metrics/BlockLength:
  Enabled: true
  Max: 35
  Exclude:
    - "spec/**/*"
    - "app/admin/*"
    - "Gemfile"
    - "Guardfile"
    - "lib/tasks/**/*"
    - "app/models/concerns/searchable/*"
    - "lib/capistrano/tasks/**/*"
    - "db/schema.rb"
    - "app/batches/workers/search_hotels_worker_batch.rb"
    - "config/**/*"
    - "app/models/labeled_data_set_carousel_flight_detail.rb"

Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - "lib/tasks/**/*"
    - "app/batches/tripadvisors/activities/scrape_all_batch.rb"
    - "app/batches/tripadvisors/hotels/scrape_all_batch.rb"
    - "app/batches/tripadvisors/restaurants/scrape_all_batch.rb"
    - "app/workers/chat_unit_updater_worker.rb"
    - "app/usecases/labeled_data_sets/create_messages_usecase.rb"

Rails/ReversibleMigration:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/OutputSafety:
  Enabled: true
  Exclude:
    - "app/helpers/application_helper.rb"
Rails/DynamicFindBy:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false